/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telacondominio;

import administacao.Adm;
import administacao.ListaAdministradores;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author leafar
 */
public class frmGeral extends javax.swing.JFrame {

    /**
     * Creates new form frmGeral
     */
    public frmGeral() {
        initComponents();
        Icon i = lblIconBemVindo.getIcon();
        ImageIcon icon = (ImageIcon) i;
        Image image = icon.getImage().getScaledInstance(lblIconBemVindo.getWidth(), lblIconBemVindo.getHeight(), Image.SCALE_SMOOTH);
        lblIconBemVindo.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCadastro = new javax.swing.JPanel();
        pnInicio = new javax.swing.JPanel();
        lblIconBemVindo = new javax.swing.JLabel();
        pnCadastroMorador = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblBloco = new javax.swing.JLabel();
        comboBloco = new javax.swing.JComboBox<>();
        lblApartamento = new javax.swing.JLabel();
        comboBloco1 = new javax.swing.JComboBox<>();
        pnCadastroAdm = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pasSenha = new javax.swing.JPasswordField();
        btnCriar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        menubarMenu = new javax.swing.JMenuBar();
        mCadastros = new javax.swing.JMenu();
        mmCadastroMorador = new javax.swing.JMenuItem();
        mmCadastroAdministrador = new javax.swing.JMenuItem();
        mSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        pnCadastro.setLayout(new java.awt.CardLayout());

        pnInicio.setBackground(new java.awt.Color(102, 102, 102));

        lblIconBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telacondominio/iconBemVindo.png"))); // NOI18N

        javax.swing.GroupLayout pnInicioLayout = new javax.swing.GroupLayout(pnInicio);
        pnInicio.setLayout(pnInicioLayout);
        pnInicioLayout.setHorizontalGroup(
            pnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInicioLayout.createSequentialGroup()
                .addComponent(lblIconBemVindo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnInicioLayout.setVerticalGroup(
            pnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInicioLayout.createSequentialGroup()
                .addComponent(lblIconBemVindo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnCadastro.add(pnInicio, "telaAdm");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome");

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCPF.setText("CPF");

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelefone.setText("Telefone");

        lblBloco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBloco.setText("Bloco");

        comboBloco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        lblApartamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblApartamento.setText("Apartamento");

        comboBloco1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout pnCadastroMoradorLayout = new javax.swing.GroupLayout(pnCadastroMorador);
        pnCadastroMorador.setLayout(pnCadastroMoradorLayout);
        pnCadastroMoradorLayout.setHorizontalGroup(
            pnCadastroMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroMoradorLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(pnCadastroMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnCadastroMoradorLayout.createSequentialGroup()
                        .addGroup(pnCadastroMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblCPF))
                        .addGap(28, 28, 28)
                        .addGroup(pnCadastroMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnCadastroMoradorLayout.createSequentialGroup()
                        .addGroup(pnCadastroMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnCadastroMoradorLayout.createSequentialGroup()
                                .addComponent(lblTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCadastroMoradorLayout.createSequentialGroup()
                                .addComponent(lblBloco)
                                .addGap(32, 32, 32)))
                        .addGroup(pnCadastroMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnCadastroMoradorLayout.createSequentialGroup()
                                .addComponent(comboBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblApartamento)
                                .addGap(32, 32, 32)
                                .addComponent(comboBloco1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        pnCadastroMoradorLayout.setVerticalGroup(
            pnCadastroMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroMoradorLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(pnCadastroMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCadastroMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPF))
                .addGap(18, 18, 18)
                .addGroup(pnCadastroMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone))
                .addGap(18, 18, 18)
                .addGroup(pnCadastroMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCadastroMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblApartamento)
                        .addComponent(comboBloco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCadastroMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBloco)
                        .addComponent(comboBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pnCadastro.add(pnCadastroMorador, "telaMorador");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario.setText("Usuário: ");

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSenha.setText("Senha:");

        btnCriar.setText("Criar");
        btnCriar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCadastroAdmLayout = new javax.swing.GroupLayout(pnCadastroAdm);
        pnCadastroAdm.setLayout(pnCadastroAdmLayout);
        pnCadastroAdmLayout.setHorizontalGroup(
            pnCadastroAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroAdmLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(pnCadastroAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnCadastroAdmLayout.createSequentialGroup()
                        .addGroup(pnCadastroAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addComponent(lblSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnCadastroAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario)
                            .addComponent(pasSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnCadastroAdmLayout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        pnCadastroAdmLayout.setVerticalGroup(
            pnCadastroAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroAdmLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(pnCadastroAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCadastroAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(pasSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(pnCadastroAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriar)
                    .addComponent(btnCancelar))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pnCadastro.add(pnCadastroAdm, "card4");

        mCadastros.setBackground(new java.awt.Color(224, 223, 246));
        mCadastros.setBorder(mSair.getBorder());
        mCadastros.setText("Cadastro");

        mmCadastroMorador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mmCadastroMorador.setText("Morador");
        mmCadastroMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmCadastroMoradorActionPerformed(evt);
            }
        });
        mCadastros.add(mmCadastroMorador);

        mmCadastroAdministrador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mmCadastroAdministrador.setText("Administrador");
        mmCadastroAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmCadastroAdministradorActionPerformed(evt);
            }
        });
        mCadastros.add(mmCadastroAdministrador);

        menubarMenu.add(mCadastros);

        mSair.setText("Sair");
        mSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSairMouseClicked(evt);
            }
        });
        menubarMenu.add(mSair);

        setJMenuBar(menubarMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mmCadastroMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmCadastroMoradorActionPerformed
        pnCadastro.removeAll();
        pnCadastro.add(pnCadastroMorador);
        pnCadastro.repaint();
        pnCadastro.revalidate();
    }//GEN-LAST:event_mmCadastroMoradorActionPerformed
    
    private void mmCadastroAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmCadastroAdministradorActionPerformed
        // TODO add your handling code here:
        pnCadastro.removeAll();
        pnCadastro.add(pnCadastroAdm);
        pnCadastro.repaint();
        pnCadastro.revalidate();
        
        
    }//GEN-LAST:event_mmCadastroAdministradorActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        // TODO add your handling code here:
        String usuario = txtUsuario.getText();
        String password = new String(pasSenha.getPassword());
        
        if(usuario.equals("") || password.equals("") || usuario.startsWith(" ") || password.startsWith(" ") ){
            JOptionPane.showMessageDialog(null, "Um dos campos está vazio!", "Campo vazio", HEIGHT);
            txtUsuario.requestFocus();
        }else{
            int flag = JOptionPane.showConfirmDialog(null, "Deseja realmente criar este usuário?\nUsuário: "+usuario+".","Confirmação",JOptionPane.YES_NO_OPTION);
            if (flag == JOptionPane.YES_OPTION){
                Adm novoAdm = new Adm(usuario, password);
                ListaAdministradores listaAdms = new ListaAdministradores();
                listaAdms.adicionarAdministrador(novoAdm);
                JOptionPane.showMessageDialog(null, "Um novo adiministrador foi adicionado!", 
                                        "Adiministrador criado.", JOptionPane.INFORMATION_MESSAGE);
                txtUsuario.setText("");
                pasSenha.setText("");
                txtUsuario.requestFocus();
            }else{
                txtUsuario.setText("");
                pasSenha.setText("");
                txtUsuario.requestFocus();
            }
        }
        
    }//GEN-LAST:event_btnCriarActionPerformed

    private void mSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSairMouseClicked
        // TODO add your handling code here:
        frmLogin frameLogin = new frmLogin();
        frameLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mSairMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        String usuario = txtUsuario.getText();
        String password = new String(pasSenha.getPassword());
        int flag = JOptionPane.showConfirmDialog(null, "Deseja cancelar o cadastro?","Cancelar cadastro",JOptionPane.YES_NO_OPTION);
            if (flag == JOptionPane.YES_OPTION){
                txtUsuario.setText("");
                pasSenha.setText("");
                pnCadastro.removeAll();
                pnCadastro.add(pnInicio);
                pnCadastro.repaint();
                pnCadastro.revalidate();
            }else{
                txtUsuario.requestFocus();
            }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGeral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JComboBox<String> comboBloco;
    private javax.swing.JComboBox<String> comboBloco1;
    private javax.swing.JLabel lblApartamento;
    private javax.swing.JLabel lblBloco;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblIconBemVindo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu mCadastros;
    private javax.swing.JMenu mSair;
    private javax.swing.JMenuBar menubarMenu;
    private javax.swing.JMenuItem mmCadastroAdministrador;
    private javax.swing.JMenuItem mmCadastroMorador;
    private javax.swing.JPasswordField pasSenha;
    private javax.swing.JPanel pnCadastro;
    private javax.swing.JPanel pnCadastroAdm;
    private javax.swing.JPanel pnCadastroMorador;
    private javax.swing.JPanel pnInicio;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
