/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telacondominio;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import administacao.ListaAdministradores;
import administacao.Adm;
import javax.swing.JOptionPane;

/**
 *
 * @author leafar
 */
public class frmRemoverAdiministrador extends javax.swing.JFrame {

    /**
     * Creates new form frmRemoverAdiministrador
     */
    public frmRemoverAdiministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRemoverMorador = new javax.swing.JLabel();
        cbAdiministradores = new javax.swing.JComboBox<>();
        btnRemoverAdimin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblRemoverMorador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRemoverMorador.setText("Remover Adiministrador");

        btnRemoverAdimin.setText("Remover");
        btnRemoverAdimin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverAdiminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(cbAdiministradores, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(btnRemoverAdimin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(lblRemoverMorador)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblRemoverMorador)
                .addGap(32, 32, 32)
                .addComponent(cbAdiministradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnRemoverAdimin)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverAdiminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverAdiminActionPerformed
        // TODO add your handling code here:
        String nome = (String) cbAdiministradores.getSelectedItem();
        if(nome == null){
            JOptionPane.showMessageDialog(null, "Não há adiministradores para remover.", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }else{
            int flag = JOptionPane.showConfirmDialog(null, "Deseja realmente remover o seguinte adiministrador?\n"
                    + "Adimin: "+nome,
                    "Confirmação",JOptionPane.YES_NO_OPTION);
                if (flag == JOptionPane.YES_OPTION){
                    ListaAdministradores listaAdimins = new ListaAdministradores();
                    boolean foiRemovido = listaAdimins.removeAdimin(nome);
                    if(foiRemovido){
                        JOptionPane.showMessageDialog(null, "Adiministrador removido!");
                    }else{
                        JOptionPane.showMessageDialog(null, "Adiministrador não foi encontrado!");
                    }
                }else{
                    cbAdiministradores.requestFocus();
                }
        }
    }//GEN-LAST:event_btnRemoverAdiminActionPerformed
    
    public void carregaCbBoxesRemoverAdimin(){
        ListaAdministradores listaAdministradores = new ListaAdministradores();
        List<Adm> adimins = listaAdministradores.getAdministradores();
        int count = 0;
        DefaultComboBoxModel<String> comboBoxModelAdimins = new DefaultComboBoxModel<>();
        for (Adm adm : adimins){
            if(count > 0){
                String nome = adm.getUsuario();
                comboBoxModelAdimins.addElement(nome);
            }
            count++;
        }
        cbAdiministradores.setModel(comboBoxModelAdimins);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRemoverAdiministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRemoverAdiministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRemoverAdiministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRemoverAdiministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRemoverAdiministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoverAdimin;
    private javax.swing.JComboBox<String> cbAdiministradores;
    private javax.swing.JLabel lblRemoverMorador;
    // End of variables declaration//GEN-END:variables
}
