/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telacondominio;

import morador.ListaMoradores;
import morador.Morador;

import javax.swing.table.TableRowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author leafar
 */
public class frmRemoveMorador extends javax.swing.JFrame {

    /**
     * Creates new form frmRemoveMorador
     */
    public frmRemoveMorador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new javax.swing.JPanel();
        pnFormRemove = new javax.swing.JPanel();
        lblRemoverMorador = new javax.swing.JLabel();
        btnRemoverMorador = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMoradores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remover morador");
        setBackground(new java.awt.Color(112, 188, 207));
        setMaximumSize(new java.awt.Dimension(697, 370));
        setMinimumSize(new java.awt.Dimension(697, 370));
        setSize(new java.awt.Dimension(697, 370));

        pnPrincipal.setBackground(new java.awt.Color(112, 188, 207));

        pnFormRemove.setBackground(new java.awt.Color(112, 188, 207));

        lblRemoverMorador.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblRemoverMorador.setForeground(new java.awt.Color(255, 255, 255));
        lblRemoverMorador.setText("Remover Morador");

        btnRemoverMorador.setText("Remover");
        btnRemoverMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverMoradorActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbMoradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMoradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMoradoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMoradores);

        javax.swing.GroupLayout pnFormRemoveLayout = new javax.swing.GroupLayout(pnFormRemove);
        pnFormRemove.setLayout(pnFormRemoveLayout);
        pnFormRemoveLayout.setHorizontalGroup(
            pnFormRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormRemoveLayout.createSequentialGroup()
                .addGroup(pnFormRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFormRemoveLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnFormRemoveLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(lblRemoverMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnFormRemoveLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(btnRemoverMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        pnFormRemoveLayout.setVerticalGroup(
            pnFormRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormRemoveLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblRemoverMorador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoverMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(pnFormRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnFormRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverMoradorActionPerformed
        // TODO add your handling code here:
        ListaMoradores listaMoradores = new ListaMoradores();
        int linhaSelecionada = tbMoradores.getSelectedRow();
        if(linhaSelecionada != -1){
            try{
                String nome = tbMoradores.getValueAt(linhaSelecionada, 0).toString();
                String cpf = tbMoradores.getValueAt(linhaSelecionada, 1).toString();
                int bloco = Integer.parseInt(tbMoradores.getValueAt(linhaSelecionada, 2).toString());
                int numAp = Integer.parseInt(tbMoradores.getValueAt(linhaSelecionada, 3).toString());
                int flag = JOptionPane.showConfirmDialog(null, "Deseja realmente remover o "
                        + "seguinte morador?\nMorador: "+nome+"\nCPF: "+cpf+ "\nBloco: "+bloco+"\nApartamento: "+numAp,
                    "Confirmação",JOptionPane.YES_NO_OPTION);
                if (flag == JOptionPane.YES_OPTION){
                    boolean removido = listaMoradores.removerMorador(nome, cpf, bloco, numAp);
                    if (removido) {
                        // Remover a linha da tabela
                        carregaMoradoresNaTabela();
                        JOptionPane.showMessageDialog( null, "Morador removido com sucesso!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Falha ao remover o morador.");
                    }
                }
            }catch(HeadlessException | NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Erro ao remover.", 
                        "Erro", JOptionPane.ERROR_MESSAGE);
            } 
        }else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para remover o morador.");
        }
    }//GEN-LAST:event_btnRemoverMoradorActionPerformed

    private void tbMoradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMoradoresMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
            int row = tbMoradores.rowAtPoint(evt.getPoint());
            tbMoradores.setRowSelectionInterval(row, row);
        }
    }//GEN-LAST:event_tbMoradoresMouseClicked
    
    public void carregaMoradoresNaTabela(){
        
        ListaMoradores listaMoradores = new ListaMoradores();
        // Define um coluna para a tabela
        String[] colunas = {"Nome", "CPF", "Bloco", "Apartamento"};
        
        DefaultTableModel tableModel = new DefaultTableModel(colunas, 0){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        List<Morador> moradores = listaMoradores.getMoradores();
        for (Morador morador : moradores) {
            Object[] rowData = {
                    morador.getNome(),
                    morador.getCpf(),
                    morador.getBloco(),
                    morador.getNumAp(),
            };
            tableModel.addRow(rowData);
        }
        tbMoradores.setModel(tableModel);
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tableModel);
        tbMoradores.setRowSorter(sorter);
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRemoveMorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRemoveMorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRemoveMorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRemoveMorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRemoveMorador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoverMorador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRemoverMorador;
    private javax.swing.JPanel pnFormRemove;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JTable tbMoradores;
    // End of variables declaration//GEN-END:variables
}
