/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telacondominio;

import infracao.Infracao;
import infracao.ListaInfracoes;
import morador.ListaMoradores;
import morador.Morador;

import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Sparq
 */
public class frmRemoveMorador extends javax.swing.JFrame {

    /**
     * Creates new form frmRemoveMorador
     */
    public frmRemoveMorador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMoradores = new javax.swing.JComboBox<>();
        cbBloco = new javax.swing.JComboBox<>();
        cbApartamento = new javax.swing.JComboBox<>();
        lblRemoverMorador = new javax.swing.JLabel();
        lblMorador = new javax.swing.JLabel();
        lblBloco = new javax.swing.JLabel();
        lblApartamento = new javax.swing.JLabel();
        btnRemoverMorador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remover morador");
        setMaximumSize(new java.awt.Dimension(697, 370));
        setSize(new java.awt.Dimension(697, 370));

        cbBloco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cbApartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        lblRemoverMorador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRemoverMorador.setText("Remover Morador");

        lblMorador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMorador.setText("Morador");

        lblBloco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBloco.setText("Bloco");

        lblApartamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblApartamento.setText("Apartamento");

        btnRemoverMorador.setText("Remover");
        btnRemoverMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverMoradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 187, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMoradores, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMorador))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBloco)
                    .addComponent(cbBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApartamento)
                    .addComponent(cbApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(184, 184, 184))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(lblRemoverMorador))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(btnRemoverMorador)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblRemoverMorador)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMorador)
                    .addComponent(lblBloco)
                    .addComponent(lblApartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMoradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnRemoverMorador)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverMoradorActionPerformed
        // TODO add your handling code here:
        String nomeCpfSelecionado = (String) cbMoradores.getSelectedItem();
        try{
            String nome = nomeCpfSelecionado.substring(0, nomeCpfSelecionado.indexOf("("));
            String cpf = nomeCpfSelecionado.substring(nomeCpfSelecionado.indexOf("(")+1, nomeCpfSelecionado.indexOf(")"));
            int bloco = Integer.parseInt((String)cbBloco.getSelectedItem());
            int apartamento = Integer.parseInt((String) cbApartamento.getSelectedItem());

            int flag = JOptionPane.showConfirmDialog(null, "Deseja realmente remover o seguinte morador?\n"
                    + "Morador: "
                    +nome+".\nCpf: "+cpf+"\nBloco: "+bloco+".\nApartamento: "+apartamento,
                    "Confirmação",JOptionPane.YES_NO_OPTION);
                if (flag == JOptionPane.YES_OPTION){
                    ListaMoradores listaMoradores = new ListaMoradores();
                    boolean foiRemovido = listaMoradores.removerMorador(nome, cpf, bloco, apartamento);
                    if(foiRemovido){
                        JOptionPane.showMessageDialog(null, "Morador removido!");
                    }else{
                        JOptionPane.showMessageDialog(null, "Morador não foi encontrado!");
                    }
                }else{
                    cbMoradores.requestFocus();
                }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "O campo morador está vazio.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoverMoradorActionPerformed
    public void carregaCbBoxesRemoverMorador(){
        ListaMoradores listaMoradores = new ListaMoradores();
        List<Morador> moradores = listaMoradores.getMoradores();
        
        DefaultComboBoxModel<String> comboBoxModelMoradores = new DefaultComboBoxModel<>();
        for (Morador morador : moradores){
            String nomeCpf = morador.getNome() +"("+morador.getCpf()+")";
            comboBoxModelMoradores.addElement(nomeCpf); // Adiciona no cb o nome dos moradores com CPF
        }
        cbMoradores.setModel(comboBoxModelMoradores);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRemoveMorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRemoveMorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRemoveMorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRemoveMorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRemoveMorador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoverMorador;
    private javax.swing.JComboBox<String> cbApartamento;
    private javax.swing.JComboBox<String> cbBloco;
    private javax.swing.JComboBox<String> cbMoradores;
    private javax.swing.JLabel lblApartamento;
    private javax.swing.JLabel lblBloco;
    private javax.swing.JLabel lblMorador;
    private javax.swing.JLabel lblRemoverMorador;
    // End of variables declaration//GEN-END:variables
}
